version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none

  enable:
    # Реальные ошибки
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

    # Работа с ошибками
    - errorlint
    - nilerr
    - nilnil

    # Работа с ресурсами
    - bodyclose
    - rowserrcheck

    # Context
    - noctx

    # Go-подводные камни
    - copyloopvar

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
