// Code generated by MockGen. DO NOT EDIT.
// Source: server/internal/submit/repository.go
//
// Generated by this command:
//
//	mockgen -destination=server/internal/submit/mock_repository_test.go -package=submit -source=server/internal/submit/repository.go RepositoryInterface
//

// Package submit is a generated GoMock package.
package submit

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepositoryInterface) Create(ctx context.Context, submission Submission) (Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, submission)
	ret0, _ := ret[0].(Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryInterfaceMockRecorder) Create(ctx, submission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositoryInterface)(nil).Create), ctx, submission)
}

// Delete mocks base method.
func (m *MockRepositoryInterface) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepositoryInterface)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRepositoryInterface) GetByID(ctx context.Context, id string) (Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByID), ctx, id)
}

// ListByTaskID mocks base method.
func (m *MockRepositoryInterface) ListByTaskID(ctx context.Context, taskID string, limit, offset int) ([]Submission, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTaskID", ctx, taskID, limit, offset)
	ret0, _ := ret[0].([]Submission)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByTaskID indicates an expected call of ListByTaskID.
func (mr *MockRepositoryInterfaceMockRecorder) ListByTaskID(ctx, taskID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTaskID", reflect.TypeOf((*MockRepositoryInterface)(nil).ListByTaskID), ctx, taskID, limit, offset)
}

// ListByUserID mocks base method.
func (m *MockRepositoryInterface) ListByUserID(ctx context.Context, userID string, limit, offset int) ([]Submission, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]Submission)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) ListByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).ListByUserID), ctx, userID, limit, offset)
}

// UpdateResult mocks base method.
func (m *MockRepositoryInterface) UpdateResult(ctx context.Context, id string, status Status, output, errMsg string) (Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResult", ctx, id, status, output, errMsg)
	ret0, _ := ret[0].(Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResult indicates an expected call of UpdateResult.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateResult(ctx, id, status, output, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResult", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateResult), ctx, id, status, output, errMsg)
}
