// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: checker/proto/judge.proto

package judgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	Status_STATUS_WA          Status = 2
	Status_STATUS_RE          Status = 3
	Status_STATUS_CE          Status = 4
	Status_STATUS_TL          Status = 5
	Status_STATUS_ML          Status = 6
	Status_STATUS_ERROR       Status = 7
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_WA",
		3: "STATUS_RE",
		4: "STATUS_CE",
		5: "STATUS_TL",
		6: "STATUS_ML",
		7: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_WA":          2,
		"STATUS_RE":          3,
		"STATUS_CE":          4,
		"STATUS_TL":          5,
		"STATUS_ML":          6,
		"STATUS_ERROR":       7,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_checker_proto_judge_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_checker_proto_judge_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_checker_proto_judge_proto_rawDescGZIP(), []int{0}
}

type PullTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTaskRequest) Reset() {
	*x = PullTaskRequest{}
	mi := &file_checker_proto_judge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTaskRequest) ProtoMessage() {}

func (x *PullTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_judge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTaskRequest.ProtoReflect.Descriptor instead.
func (*PullTaskRequest) Descriptor() ([]byte, []int) {
	return file_checker_proto_judge_proto_rawDescGZIP(), []int{0}
}

type PullTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTaskResponse) Reset() {
	*x = PullTaskResponse{}
	mi := &file_checker_proto_judge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTaskResponse) ProtoMessage() {}

func (x *PullTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_judge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTaskResponse.ProtoReflect.Descriptor instead.
func (*PullTaskResponse) Descriptor() ([]byte, []int) {
	return file_checker_proto_judge_proto_rawDescGZIP(), []int{1}
}

func (x *PullTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	TestCases     []*TestCase            `protobuf:"bytes,5,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_checker_proto_judge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_judge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_checker_proto_judge_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *Task) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Task) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Task) GetTestCases() []*TestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

type TestCase struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Number         int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Input          string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	ExpectedOutput string                 `protobuf:"bytes,3,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_checker_proto_judge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_judge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_checker_proto_judge_proto_rawDescGZIP(), []int{3}
}

func (x *TestCase) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *TestCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCase) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

type SubmitResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=judge.v1.Status" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultRequest) Reset() {
	*x = SubmitResultRequest{}
	mi := &file_checker_proto_judge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultRequest) ProtoMessage() {}

func (x *SubmitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_judge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitResultRequest) Descriptor() ([]byte, []int) {
	return file_checker_proto_judge_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitResultRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *SubmitResultRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *SubmitResultRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *SubmitResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubmitResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultResponse) Reset() {
	*x = SubmitResultResponse{}
	mi := &file_checker_proto_judge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultResponse) ProtoMessage() {}

func (x *SubmitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_judge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitResultResponse) Descriptor() ([]byte, []int) {
	return file_checker_proto_judge_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_checker_proto_judge_proto protoreflect.FileDescriptor

const file_checker_proto_judge_proto_rawDesc = "" +
	"\n" +
	"\x19checker/proto/judge.proto\x12\bjudge.v1\"\x11\n" +
	"\x0fPullTaskRequest\"6\n" +
	"\x10PullTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.judge.v1.TaskR\x04task\"\x8e\x01\n" +
	"\x04Task\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x121\n" +
	"\n" +
	"test_cases\x18\x05 \x03(\v2\x12.judge.v1.TestCaseR\ttestCases\"a\n" +
	"\bTestCase\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12'\n" +
	"\x0fexpected_output\x18\x03 \x01(\tR\x0eexpectedOutput\"\x92\x01\n" +
	"\x13SubmitResultRequest\x12#\n" +
	"\rsubmission_id\x18\x02 \x01(\tR\fsubmissionId\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.judge.v1.StatusR\x06status\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"2\n" +
	"\x14SubmitResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*\x8c\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\r\n" +
	"\tSTATUS_WA\x10\x02\x12\r\n" +
	"\tSTATUS_RE\x10\x03\x12\r\n" +
	"\tSTATUS_CE\x10\x04\x12\r\n" +
	"\tSTATUS_TL\x10\x05\x12\r\n" +
	"\tSTATUS_ML\x10\x06\x12\x10\n" +
	"\fSTATUS_ERROR\x10\a2\x9f\x01\n" +
	"\vCoordinator\x12A\n" +
	"\bPullTask\x12\x19.judge.v1.PullTaskRequest\x1a\x1a.judge.v1.PullTaskResponse\x12M\n" +
	"\fSubmitResult\x12\x1d.judge.v1.SubmitResultRequest\x1a\x1e.judge.v1.SubmitResultResponseBAZ?github.com/meytardzhevtd/CodeTest/checker/internal/grpc/judgepbb\x06proto3"

var (
	file_checker_proto_judge_proto_rawDescOnce sync.Once
	file_checker_proto_judge_proto_rawDescData []byte
)

func file_checker_proto_judge_proto_rawDescGZIP() []byte {
	file_checker_proto_judge_proto_rawDescOnce.Do(func() {
		file_checker_proto_judge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checker_proto_judge_proto_rawDesc), len(file_checker_proto_judge_proto_rawDesc)))
	})
	return file_checker_proto_judge_proto_rawDescData
}

var file_checker_proto_judge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_checker_proto_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_checker_proto_judge_proto_goTypes = []any{
	(Status)(0),                  // 0: judge.v1.Status
	(*PullTaskRequest)(nil),      // 1: judge.v1.PullTaskRequest
	(*PullTaskResponse)(nil),     // 2: judge.v1.PullTaskResponse
	(*Task)(nil),                 // 3: judge.v1.Task
	(*TestCase)(nil),             // 4: judge.v1.TestCase
	(*SubmitResultRequest)(nil),  // 5: judge.v1.SubmitResultRequest
	(*SubmitResultResponse)(nil), // 6: judge.v1.SubmitResultResponse
}
var file_checker_proto_judge_proto_depIdxs = []int32{
	3, // 0: judge.v1.PullTaskResponse.task:type_name -> judge.v1.Task
	4, // 1: judge.v1.Task.test_cases:type_name -> judge.v1.TestCase
	0, // 2: judge.v1.SubmitResultRequest.status:type_name -> judge.v1.Status
	1, // 3: judge.v1.Coordinator.PullTask:input_type -> judge.v1.PullTaskRequest
	5, // 4: judge.v1.Coordinator.SubmitResult:input_type -> judge.v1.SubmitResultRequest
	2, // 5: judge.v1.Coordinator.PullTask:output_type -> judge.v1.PullTaskResponse
	6, // 6: judge.v1.Coordinator.SubmitResult:output_type -> judge.v1.SubmitResultResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_checker_proto_judge_proto_init() }
func file_checker_proto_judge_proto_init() {
	if File_checker_proto_judge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checker_proto_judge_proto_rawDesc), len(file_checker_proto_judge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checker_proto_judge_proto_goTypes,
		DependencyIndexes: file_checker_proto_judge_proto_depIdxs,
		EnumInfos:         file_checker_proto_judge_proto_enumTypes,
		MessageInfos:      file_checker_proto_judge_proto_msgTypes,
	}.Build()
	File_checker_proto_judge_proto = out.File
	file_checker_proto_judge_proto_goTypes = nil
	file_checker_proto_judge_proto_depIdxs = nil
}
