// Code generated by MockGen. DO NOT EDIT.
// Source: server/internal/tasks/repository.go
//
// Generated by this command:
//
//	mockgen -destination=server/internal/tasks/mock_repository_test.go -package=tasks -source=server/internal/tasks/repository.go RepositoryInterface
//

// Package tasks is a generated GoMock package.
package tasks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddTagsToTask mocks base method.
func (m *MockRepositoryInterface) AddTagsToTask(ctx context.Context, taskID string, tagNames []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTagsToTask", ctx, taskID, tagNames)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTagsToTask indicates an expected call of AddTagsToTask.
func (mr *MockRepositoryInterfaceMockRecorder) AddTagsToTask(ctx, taskID, tagNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTagsToTask", reflect.TypeOf((*MockRepositoryInterface)(nil).AddTagsToTask), ctx, taskID, tagNames)
}

// CreateTask mocks base method.
func (m *MockRepositoryInterface) CreateTask(ctx context.Context, task Task) (Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task)
	ret0, _ := ret[0].(Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockRepositoryInterfaceMockRecorder) CreateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateTask), ctx, task)
}

// DeleteTask mocks base method.
func (m *MockRepositoryInterface) DeleteTask(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteTask), ctx, id)
}

// GetTaskByID mocks base method.
func (m *MockRepositoryInterface) GetTaskByID(ctx context.Context, id string) (Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, id)
	ret0, _ := ret[0].(Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetTaskByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTaskByID), ctx, id)
}

// GetTaskBySlug mocks base method.
func (m *MockRepositoryInterface) GetTaskBySlug(ctx context.Context, slug string) (Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskBySlug", ctx, slug)
	ret0, _ := ret[0].(Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskBySlug indicates an expected call of GetTaskBySlug.
func (mr *MockRepositoryInterfaceMockRecorder) GetTaskBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskBySlug", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTaskBySlug), ctx, slug)
}

// ListTasks mocks base method.
func (m *MockRepositoryInterface) ListTasks(ctx context.Context, limit, offset int) ([]Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, limit, offset)
	ret0, _ := ret[0].([]Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockRepositoryInterfaceMockRecorder) ListTasks(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockRepositoryInterface)(nil).ListTasks), ctx, limit, offset)
}

// SetExamples mocks base method.
func (m *MockRepositoryInterface) SetExamples(ctx context.Context, taskID string, examples []ExampleInput) ([]Example, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExamples", ctx, taskID, examples)
	ret0, _ := ret[0].([]Example)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetExamples indicates an expected call of SetExamples.
func (mr *MockRepositoryInterfaceMockRecorder) SetExamples(ctx, taskID, examples any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExamples", reflect.TypeOf((*MockRepositoryInterface)(nil).SetExamples), ctx, taskID, examples)
}

// SetTags mocks base method.
func (m *MockRepositoryInterface) SetTags(ctx context.Context, taskID string, tagNames []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTags", ctx, taskID, tagNames)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTags indicates an expected call of SetTags.
func (mr *MockRepositoryInterfaceMockRecorder) SetTags(ctx, taskID, tagNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTags", reflect.TypeOf((*MockRepositoryInterface)(nil).SetTags), ctx, taskID, tagNames)
}

// UpdateTask mocks base method.
func (m *MockRepositoryInterface) UpdateTask(ctx context.Context, id string, updates Task) (Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, id, updates)
	ret0, _ := ret[0].(Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateTask(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateTask), ctx, id, updates)
}
