// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/storage/interfaces.go
//
// Generated by this command:
//
//	mockgen -destination=server/internal/tasks/mock_storage_test.go -package=tasks -source=pkg/storage/interfaces.go Writer
//

// Package tasks is a generated GoMock package.
package tasks

import (
	context "context"
	io "io"
	reflect "reflect"

	storage "github.com/meytardzhevtd/CodeTest/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// GetTest mocks base method.
func (m *MockReader) GetTest(ctx context.Context, tc storage.TestCase) (io.ReadCloser, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTest", ctx, tc)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTest indicates an expected call of GetTest.
func (mr *MockReaderMockRecorder) GetTest(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTest", reflect.TypeOf((*MockReader)(nil).GetTest), ctx, tc)
}

// ListTests mocks base method.
func (m *MockReader) ListTests(ctx context.Context, taskID string) ([]storage.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTests", ctx, taskID)
	ret0, _ := ret[0].([]storage.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTests indicates an expected call of ListTests.
func (mr *MockReaderMockRecorder) ListTests(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTests", reflect.TypeOf((*MockReader)(nil).ListTests), ctx, taskID)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// DeleteTask mocks base method.
func (m *MockWriter) DeleteTask(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockWriterMockRecorder) DeleteTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockWriter)(nil).DeleteTask), ctx, taskID)
}

// UploadTest mocks base method.
func (m *MockWriter) UploadTest(ctx context.Context, taskID string, testNum int, input io.Reader, inputSize int64, output io.Reader, outputSize int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadTest", ctx, taskID, testNum, input, inputSize, output, outputSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadTest indicates an expected call of UploadTest.
func (mr *MockWriterMockRecorder) UploadTest(ctx, taskID, testNum, input, inputSize, output, outputSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadTest", reflect.TypeOf((*MockWriter)(nil).UploadTest), ctx, taskID, testNum, input, inputSize, output, outputSize)
}
